### ISSUE TITLE
Crash when running on a dedicated server

### ISSUE THREAD

**Issue by Archund** [Brian-Wuest/MC-Prefab-Fabric#1]
Prefab causes a crash when a player builds a structure.
This only happened when prefab was installed on a dedicated server.
The crash does not happen when playing in a singleplayer world on the client.

The Fabric version used was 0.11.1
Fabric API 0.29.4 was installed.
Prefab 1.0.0 was isntalled.

[latest.log](https://github.com/Brian-Wuest/MC-Prefab-Fabric/files/5879030/latest.log)

[crash-2021-01-27_03.21.22-server.txt](https://github.com/Brian-Wuest/MC-Prefab-Fabric/files/5879032/crash-2021-01-27_03.21.22-server.txt)

**Comment by Brian-Wuest** [comment]
Blast, I thought I got that one!
Will be an easy fix.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.0.1 which is now available on CurseForge and Modrinth.
