### ISSUE TITLE
Not spawning with starter house

### ISSUE THREAD

**Issue by Feathertoes** [Brian-Wuest/MC-Prefab-Fabric#2]
No matter what I do, the default item that I set the game to start with is never consistent with whether or not I will receive it.

I've tested around with leaving the thing empty then changing it back to normal in hopes that it would register, but it seems to not work at all.

**Comment by Brian-Wuest** [comment]
Oof, this is going to be a tricky one. 

There are a couple major problems right now.

1. How the Starting Options are loading from the file is incorrect (partial fix)
2. Saving the player data per server is tricky
3. Configuration doesn't seem to be updated/loaded when joining server.

I will be working on this but it's not going to be a quick fix.

Totally my fault for not catching this during testing; sorry about that!!!

**Comment by Brian-Wuest** [comment]
This will be available on CurseForge and Modrinth when they are approved.

Thank you for finding this!
