### ISSUE TITLE
Can't view buildings in preview mode.

### ISSUE THREAD

**Issue by Cva666** [Brian-Wuest/MC-Prefab-Fabric#21]
mod version prefab-fabric-2.0.2.1
fabric version 0.11.6
minecraft version 1.17
 bug is that whenever you load up a prefab Gui it does not show the buildings it just blank. no error codes or any problems with crashes or anything

**Comment by Brian-Wuest** [comment]
Just loaded it up; works fine.

![2021-07-23_08 39 55](https://user-images.githubusercontent.com/13502068/126790271-e39b856a-1b64-4937-bc06-d66fbf6b7a3f.png)

Make sure you don't have this option turned off

![image](https://user-images.githubusercontent.com/13502068/126790393-56fd81dc-04e4-48b6-bf41-545a0c2431fa.png)


Mod List:
![image](https://user-images.githubusercontent.com/13502068/126790435-7aa4ee17-88e4-4013-8f00-1a2f096a8167.png)

**Comment by Cva666** [comment]
So lithium is required for this mod to work?

**Comment by Brian-Wuest** [comment]
It's not required. Just what I had in my modpack. The only mod required is the cloth configuration mod

**Comment by Cva666** [comment]
![mods 9](https://user-images.githubusercontent.com/87833368/126851515-d9828a52-8710-4e42-b06c-d3f3e9b302e8.png)
![mods 10](https://user-images.githubusercontent.com/87833368/126851516-317ab076-6b15-4dc1-821b-a145b1b288e5.png)
![mods 11](https://user-images.githubusercontent.com/87833368/126851517-236b210b-d99c-4379-9bb0-d8a727706909.png)
![mods 12](https://user-images.githubusercontent.com/87833368/126851518-60b65122-e316-47c0-a8de-00dd6f6e929b.png)
![mods13](https://user-images.githubusercontent.com/87833368/126851519-b684404f-8caf-44e7-b021-6738c04b0cbb.png)
![mods 14](https://user-images.githubusercontent.com/87833368/126851520-7d6b8d59-526e-43bb-8d58-245d7366d7d1.png)
![mods 15](https://user-images.githubusercontent.com/87833368/126851522-7992dbcf-130d-4122-96c5-46391d598941.png)
![2021-07-23_20 06 41](https://user-images.githubusercontent.com/87833368/126851523-74a51a3b-165c-48d9-ad0a-53ba2bf254fa.png)
![2021-07-23_20 06 23](https://user-images.githubusercontent.com/87833368/126851525-7169a880-f935-4a9d-890c-126776db7583.png)
![mods 1](https://user-images.githubusercontent.com/87833368/126851526-e05311be-3d36-4f9c-9842-55388576bab8.PNG)
![mods 2](https://user-images.githubusercontent.com/87833368/126851527-ce2f3fe0-62c4-4b2a-b00f-5604a5e8fa8f.png)
![mods 3](https://user-images.githubusercontent.com/87833368/126851528-41b60140-2957-4baf-ab6a-2de47fedaeed.png)
![mods 4](https://user-images.githubusercontent.com/87833368/126851529-662b5862-5ac8-4f71-88ff-ccb40e96fb5a.png)
![mods 5](https://user-images.githubusercontent.com/87833368/126851530-d9524fd5-1099-479c-8f09-fceee49465cc.png)
![mods 6](https://user-images.githubusercontent.com/87833368/126851532-d66f6056-f486-4380-b478-81bb2768e6da.png)
![mods 7](https://user-images.githubusercontent.com/87833368/126851533-f1a55274-e943-4efd-a246-dac9e42ab43b.png)
![mods8](https://user-images.githubusercontent.com/87833368/126851534-e6dabd7b-b96a-4dc4-b717-f0fdf3b15729.png)
this is what I get when I try to preview it in the game and this is my mods i have i made sure the settings were correct as well

**Comment by Brian-Wuest** [comment]
That's a lot of mods. Of all of the ones listed, Visual Overhaul is suspicious.

Basically another mod is interfering with the preview.

**Comment by Cva666** [comment]
Thank you for your help for future BCLib
by paulevs mod conflicts with your prieview function of your mod
