### ISSUE TITLE
[Enhancement]: Config options added

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab-Fabric#40]
### Minecraft Version

1.17.1

### Fabric Version

40.1

### Mod Version

2.1.4

### Details

Love the new farms, although, it would be great to have options in the config to set true or false on certain aspects of the tiers, as in, giving players/server owners/mod pack owners the ability to set false to for example having moderate farms and starter farms not include any automation/crops but to let the Advance Farms include them.

**Comment by Brian-Wuest** [comment]
I can add a configuration option to remove the "Automated Farm" "Sugar Cane Farm" and "Chicken Coop" from the Moderate Farm blueprint. These are the automation ones from that blueprint.

**Comment by itsdinkd** [comment]
Perfect!   From: Brian WuestSent: Saturday, September 11, 2021 9:34 AMTo: Brian-Wuest/MC-Prefab-FabricCc: red2blue; AuthorSubject: Re: [Brian-Wuest/MC-Prefab-Fabric] [Enhancement]: Config options added (#40) I can add a configuration option to remove the "Automated Farm" "Sugar Cane Farm" and "Chicken Coop" from the Moderate Farm blueprint. These are the automation ones from that blueprint.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
