### ISSUE TITLE
[Enhancement]: Add missing brick and log bulk storage as placeable decor blocks

### ISSUE THREAD

**Issue by Syndaryl** [Brian-Wuest/MC-Prefab-Fabric#44]
### Minecraft Version

1.17.1

### Fabric Version

Fabric 0.11.7

### Mod Version

2.1.6

### Details

The icons for the bulk storage blocks for bricks and log look very good, and would make good decorative items around an appropriately themed build. I'd love to have them as actual placeable blocks :)

**Comment by Brian-Wuest** [comment]
This might be a bit tricky to do but we can try it. I don't want people to lose what they already crafted but allow for blocks.
