### ISSUE TITLE
Crash while starting the game

### ISSUE THREAD

**Issue by tankyap** [Brian-Wuest/MC-Prefab-Fabric#50]
### Minecraft Version

1.17.1

### Fabric Version

Fabric loader:0.11.7
Api:0.42.1

### Mod Version

2.1.6

### Details
Literally just crashes when strat the game.

Exit code: The game crashed whilst initializing game
                Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, 
                provided by 'prefab'!
                Exit Code: -1

Crash report file: [crash-2021-11-27_21.40.39-client.txt](https://github.com/Brian-Wuest/MC-Prefab-Fabric/files/7611805/crash-2021-11-27_21.40.39-client.txt)
Lastest log file: [latest.log](https://github.com/Brian-Wuest/MC-Prefab-Fabric/files/7611817/latest.log)

**Comment by Brian-Wuest** [comment]
Looks like this might be a compatibility issue with Meteor Client. They are doing some modifications to the Minecraft code that Prefab then uses.

See the part of the log below which shows that Meteor Client is modifying something.

You can find their GitHub here: https://github.com/MeteorDevelopment/meteor-client

![image](https://user-images.githubusercontent.com/13502068/143686336-6a6648b0-450c-4e49-8878-b11603e06a4a.png)

Closing issue.
