### ISSUE TITLE
[Bug]: incompatiblity with immersive weathering

### ISSUE THREAD

**Issue by TheRanker** [Brian-Wuest/MC-Prefab-Fabric#62]
### Minecraft Version

1.18.2

### Fabric Version

0.13.3

### Mod Version

prefab-fabric-3.1.2.jar

### Details

using prefab alongside of immersive weathering, causes a crash when using certain prefab blocks. 

https://pastebin.ubuntu.com/p/bPqSZp5B3k/

its to do with 
 Cannot get property class_2746{name=fertile, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{prefab:block_grass_stairs}

**Comment by Brian-Wuest** [comment]
This is an error in Immersive Weathering that they have to fix.
