### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by ardissaps** [Brian-Wuest/MC-Prefab-Fabric#65]
### Minecraft Version

1.18.2

### Fabric Version

Any

### Details

Please include prebuilt elevator(lift) with this mods https://modrinth.com/mod/lifts (https://www.youtube.com/watch?v=LjCs5a_9FYM), the mods look so good but need complex build can save so much time if can be built instantly with Prefab. Thanks in advance! :)

**Comment by Brian-Wuest** [comment]
We are not going to integrate with other mods in this way at this time.

**Comment by ardissaps** [comment]
> We are not going to integrate with other mods in this way at this time.

Ah yes, it is ok. I found that mods very buggy, sometime we freefall after reach certain floor cause death. Pls ignore.
