### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by ixiLiam** [Brian-Wuest/MC-Prefab-Fabric#7]
My mods:
fabric-api-0.34.2
autoconfig1u-3.3.1
cloth-config-4.11.26-fabric
modmenu-1.10.6
prefab-fabric-1.0.3

Here are my logs: https://pastebin.com/sCCD28QD
Crash code: 0

**Comment by Brian-Wuest** [comment]
My guess is that with the new version of fabric api that I need to update mappings or that modmenu needs updating since it appears to be an issue with injecting mixing.

I am pretty swamped with work on the forge side of things but once that is done I can switch over to this.

**Comment by Brian-Wuest** [comment]
Forgot that this was here, should be fixed with the 1.0.4 release which is available on curseforge.
