### ISSUE TITLE
[Bug]: 1.19.2 - Crash/hang on server start-up

### ISSUE THREAD

**Issue by kwpugh** [Brian-Wuest/MC-Prefab-Fabric#70]
### Minecraft Version

1.19.2

### Fabric Version

fabric-server-1.19.2-0.14.9.jar

### Mod Version

fabric-api-0.60.0+1.19.2.jar

### Details

The server hangs and eventually crashes at start-up on a dedicated server.

Crash report: https://gist.github.com/kwpugh/a2ddae686e10b85f8abce08f0a1be897

**Comment by Brian-Wuest** [comment]
I was able to duplicate the issue though I have no idea why it didn't show up during my testing.

Got a fix and it will be available shortly.

**Comment by kwpugh** [comment]
Ok, thanks.  I will test on my test server when it comes out.

**Comment by Brian-Wuest** [comment]
It's on Modrinth already here: https://modrinth.com/mod/prefab/version/4.2.2

**Comment by kwpugh** [comment]
I fired it up, no crash.  Looks good. Thanks.
