### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZaneFlynt01** [Brian-Wuest/MC-Prefab-Fabric#71]
### Minecraft Version

1.19.2

### Fabric Version

I'm running it on quilt since it works with Fabric mods. Quilt Version is 0.17.4

### Mod Version

4.2.1

### Details

Whenever I use the Advanced House, my game crashes.

I have the crash log here: https://pastebin.com/n391Xcua

If this doesn't work, then the crash log is attatched as a .txt file
[crash-2022-09-09_17.08.48-client.txt](https://github.com/Brian-Wuest/MC-Prefab-Fabric/files/9538830/crash-2022-09-09_17.08.48-client.txt)

All the mods I'm currently using can be found at https://drive.google.com/file/d/1NyaWZK8k4eJUkLyTLSG_odsE9A3YJ9PB/view?usp=sharing

It only crashes when I right click with the Advanced House. Instead of opening the menu like normal, my game freezes when I click with the item in my hand and then crashes.

**Comment by Brian-Wuest** [comment]
While we will not directly support Quilt, I was able to duplicate the issue though I have no idea why it didn't show up during my testing.

Got a fix and it will be available shortly.
