### ISSUE TITLE
[Bug]: 1.19.2 - Client crash trying to open item GUI

### ISSUE THREAD

**Issue by kwpugh** [Brian-Wuest/MC-Prefab-Fabric#72]
### Minecraft Version

1.19.2

### Fabric Version

fabric-api-0.60.0+1.19.2.jar

### Mod Version

prefab-fabric-4.2.2.jar

### Details

crash report:  https://paste.ee/p/VhCLk

Tried to click the starter item on the ground and crashed.

**Comment by Brian-Wuest** [comment]
Grr....I tested that item specifically before releasing......

**Comment by Brian-Wuest** [comment]
I wasn't able to duplicate that locally. Can you try to delete your config file and try again?

**Comment by kwpugh** [comment]
will do.

**Comment by kwpugh** [comment]
deleting the config file fixed it.  such a simple fix.

**Comment by Brian-Wuest** [comment]
Nice! Closing issue!
