### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ardissaps** [Brian-Wuest/MC-Prefab-Fabric#73]
### Minecraft Version

1.19.2

### Fabric Version

Quilt 0.17.4

### Mod Version

4.2.2

### Details

The issue is not happening with 1.18.2 version of the mod (Prefab 3.1.5).

The issue is happened spesifically only on (to reproduce the issue) : 
1. [Iris](https://modrinth.com/mod/iris/changelog) (Tried on 1.2.8 and 1.3.1) with all its dependency.
2. Minecraft 1.19.2.
3. Prefab 4.2.2
4. Quilt 0.17.4

Latest Log
https://aofpaste.com/sifaqutuje.sql

I also have asked on Iris discord and I got some information :
![image](https://user-images.githubusercontent.com/82106625/189505475-c760db73-576d-4af9-8ff8-9d99705d4e2f.png)

@Brian-Wuest 
Thank you very much not hurry, just take your time! :)

**Comment by Brian-Wuest** [comment]
There are a lot of errors there and we don't support quilt.

Please provide the specific error in that log which is specific to Prefab as I could not see it right away.

It looks like It's is a shader mod. We don't support those mods with preview. This is similar to not supporting Optifine.
