### ISSUE TITLE
[Bug 1.19.2]: Mineshaft Entrance not placing... mineshaft.

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab-Fabric#77]
### Minecraft Version

1.19.2

### Fabric Version

0.14.13

### Mod Version

4.2.4

### Details

As title suggests, when using Mineshaft Entrance the mineshaft is not getting added. I did disable addMineShafts in the config for Starter Houses, but I want players to be able to have an actual mineshaft with the mineshaft prefab.

It seems you fixed this in a 1.19.3 version so I am requesting a back port please.

Also, if so, will this respect the false config option for the starter house not adding a mineshaft?

**Comment by Brian-Wuest** [comment]
We only support the latest version.

Please upgrade to 1.19.3.

**Comment by itsdinkd** [comment]
My pack, Aqm2 is still on 1.19.2, as well as most modpacks seeing how not many major mods are on 1.19.3. Looking at prefabs downloads your 1.19.3 version is not anywhere close as to your 1.19 2. Can you backport this fix please?

**Comment by Brian-Wuest** [comment]
Download count isn't something we look at to determine where fixes can or should go.

The team has decided what versions we support. This is to make sure we have enough capacity to fix issues or make new features.

We cannot support every version of Minecraft which we have a build for. The versions we support are described on our Discord FAQ channel.
