### ISSUE TITLE
[Bug 1.19.2]: Spawners being placed not respecting config

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab-Fabric#78]
### Minecraft Version

1.19.2

### Fabric Version

0.14.13

### Mod Version

4.2.4

### Details

![image](https://user-images.githubusercontent.com/35115304/218282715-68c5df70-4094-45c6-bf4b-1d860eab3f8b.png)

This is set to false however when placing the monster farm all the spawners are still generating.

**Comment by Brian-Wuest** [comment]
Please try this in 1.19.3.

1.19.2 is no longer supported.

**Comment by itsdinkd** [comment]
Aqm2 is still on 1.19.2, as well as most modpacks seeing how not many major
mods are on 1.19.3
