### ISSUE TITLE
[Bug]: Placing the "house" item in your inventory crashes the game on 1.19.4

### ISSUE THREAD

**Issue by Luncaaa** [Brian-Wuest/MC-Prefab-Fabric#79]
### Minecraft Version

1.19.4

### Fabric Version

0.14.18

### Mod Version

4.3.2

### Details

When joining a world in 1.19.4, if you right click the "House" item on the ground it will cause your game to crash. I attached the crash log.

https://pastebin.com/D9cwzKJJ

**Comment by Brian-Wuest** [comment]
This mod is no longer supported (no this is not a cruel Aprils Fool's joke).

The last supported version of Minecraft was 1.19.3 until someone else takes up the mantle.
